# Generated by Django 3.1.2 on 2020-10-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesion',
            options={'ordering': ['id'], 'verbose_name_plural': 'Profesiones'},
        ),
        migrations.AddField(
            model_name='persona',
            name='coordenadas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
